### PR TITLE
improvement/queueMonagraph

### PR DESCRIPTION
**Pull request by gregoryyoung2**
Hey,

I went through this and it looks good as far as Team 1's guidelines and the our assignment goes. I was thinking thinking about pushing what we have in this branch to the master for now. We'd probably remove the `main()` method and the file with a "~" suffix that JEdit creates (I believe this is an autosave). 

Normally whoever is working on the branch would create a pull request when they think it's ready to merge to the master, so feel free to create pull requests for your own branches when you think you have something ready for the master. This branch is a good example of something ready for master as it is working code that complies with the guidelines we have. If we find something later on that needs to be changed it can still be changed.

The reason for pull requests is so everyone on the team has a chance to look something over before it goes to the master branch. So before we push this to the master it would be cool if at least one person (or both) from every division of the team comments something like "Looks good!" or some kind of suggestion before this is pushed. Especially @jeremyxy and @jardean05 as they worked on this branch.

Thanks guys!

### CODE REVIEW

**Comment by jeremyxy** [comment]
Hope this pull request includes the version with updated javadoc comments but I think it's ready to be pushed to master.

**Comment by gregoryyoung2** [comment]
@jeremyxy Yup, when you add commits to a branch with an active pull request it will automatically add them to the pull request. I'm ready to merge this but lets wait for a few other people to look it over.

**Comment by willsonnate** [comment]
Looks good.

**Comment by gregoryyoung2** [comment]
Hey @jeremyxy @jardean05,

[Check out this issue before we merge](https://github.com/gregoryyoung2/CSE231Winter2016-GroupProject-Team5/issues/9)

**Pull request merged**
