### PR TITLE
Improvement/queue

### PR DESCRIPTION
**Pull request by willsonnate**

### CODE REVIEW

**Comment by willsonnate** [comment]
@gregoryyoung2 @ajstepp @msriva3242 @jeremyxy @mdjani @jardean05 
Check this over, once a few people say to go ahead I can manually merge it into the master.

**Comment by gregoryyoung2** [comment]
@willsonnate Looks good to me, if you can manually merge it that would be great!

**Comment by jeremyxy** [comment]
@willsonnate @ajstepp I may be wrong in saying this but it looked like you guys had a class variable time of type long. Then in the method for finding the odd values it looks like you declared another variable time of type long with the scope of only the method. A simple fix to this may be to write the line of code time = endTime - startTime as opposed to long time = endTime - startTime. Also, please disregard this comment if I'm wrong about this and apologies to you both!

**Comment by gregoryyoung2** [comment]
> A simple fix to this may be to write the line of code `time = endTime - startTime` as opposed to `long time = endTime - startTime`. Also, please disregard this comment if I'm wrong about this and apologies to you both!

@jeremyxy implemented amd committed

**Comment by gregoryyoung2** [comment]
@willsonnate I cleaned up the branch so it can be automatically merged. Don't worry about a manual merge.

**Comment by gregoryyoung2** [comment]
Everything looks good to me, ready to merge. Let me know what you guys think.

**Comment by willsonnate** [comment]
Looks good. Going to merge now.

**Pull request merged**
